var a = 15;
var b = 4;
var c = 0;

c=a-b;
document.write(`${a}-${b}= ${c} </br>`);
c=a**b;
document.write(`${a}**${b}= ${c} </br>`);
c=a-b;
document.write(`${a}*${b}= ${c} </br>`);
c=a/b;
document.write(`${a}/${b}= ${c} </br>`);
c=a%b;
document.write(`${a}%${b}= ${c} </br>`);
document.write("<br>");
document.write("Score Point, . .");
var score = 100;
document.write("Score= " +score+ "<br>");

score += 5;
document.write("score= "+score+"<br>");
score -= 5;
document.write("score= "+score+"<br>");
score *= 5;
document.write("score= "+score+"<br>");
score /= 5;
document.write("score= "+score+"<br>");
score **= 5;
document.write("score= "+score+"<br>");
score %= 5;
document.write("score= "+score+"<br>");
document.write("<br>");
document.write("<h1>Perbandingan</h1>");
var i = 23;
var u = 22;
var result = i == u;
document.write(`${i}==${u}= ${result} </br>`);
var result = i > u;
document.write(`${i}>${u}= ${result} </br>`);
var result = i >= u;
document.write(`${i}>=${u}= ${result} </br>`);
var result = i < u;
document.write(`${i}<${u}= ${result} </br>`);
var result = i <= u;
document.write(`${i}<=${u}= ${result} </br>`);
var result = i != u;
document.write(`${i}!=${u}= ${result} </br>`);
document.write("<br>");
document.write("<h1>Logika</h1>");
var im = 20;
var yu = 18;
var tu = im > yu;
var fal = im < yu;
var res = tu && fal;
document.write(`${tu}&& ${fal}= ${res}<br>`);
var res = tu || fal;
document.write(`${tu} || ${fal}= ${res}<br>`);
var res = !fal;
document.write(`!${fal}= ${res}<br>`);
document.write("<br>");
document.write("<h1>Bitwise0</h1>");
var x = 4;
var y = 2;
var sult = x | y;
document.write(`${x} | ${y}= ${sult}<br>`);
var sult = x ^ y;
document.write(`${x} ^ ${y}= ${sult}<br>`);
var sult = x >> y;
document.write(`${x} >> ${y}= ${sult}<br>`);
var sult = x << y;
document.write(`${x} << ${y}= ${sult}<br>`);
var sult = x >>> y;
document.write(`${x} >>> ${y}= ${sult}<br>`);
var sult = ~x;
document.write(`~${x} = ${sult}<br>`);

document.write("<br>");
document.write("<h1>Ternary</h1>")
var answer = confirm("Stay here with me...?");

var shit = answer ? "Welcome to me" : "Cant stay here";
document.write(shit);